---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

steps:
  - name: generate
    image: golang:1.19
    commands:
      - go run cmd/generate.go

  - name: gitignore
    image: thegeeklab/alpine-tools
    commands:
      - sed -i '/^README.md$/d' .gitignore

  - name: markdownlint
    image: thegeeklab/markdownlint-cli
    commands:
      - markdownlint 'README.md'

  - name: spellcheck
    image: thegeeklab/alpine-tools
    commands:
      - spellchecker --files 'README.md' -d .dictionary -p spell indefinite-article syntax-urls --no-suggestions
    environment:
      FORCE_COLOR: true
      NPM_CONFIG_LOGLEVEL: error

  - name: publish
    image: thegeeklab/drone-git-action
    settings:
      actions:
        - commit
        - push
      author_email: bot@thegeeklab.de
      author_name: thegeeklab-bot
      branch: main
      message: "[skip ci] automated readme update"
      netrc_password:
        from_secret: github_token
    when:
      ref:
        exclude:
          - refs/pull/**

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: signature
hmac: e661dbf9e5a9be42b870964c3ba1ccc785b33ef47f665e1ac9bae5ec9782ef64

...
