---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  generate:
    image: docker.io/library/golang
    commands:
      - go run cmd/generate.go

  markdownlint:
    image: quay.io/thegeeklab/markdownlint-cli
    commands:
      - markdownlint 'README.md'

  spellcheck:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - spellchecker --files 'content/**/*.md' 'README.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"
      NPM_CONFIG_LOGLEVEL: error

  publish:
    image: quay.io/thegeeklab/wp-git-action
    settings:
      action:
        - commit
        - push
      author_email: bot@thegeeklab.de
      author_name: thegeeklab-bot
      message: "[skip ci] automated readme update"
      netrc_password:
        from_secret: github_token
      commands:
        - echo $PLUGIN_AUTHOR_EMAIL
        - echo $PLUGIN_ACTION
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
