---
when:
  - event: [pull_request, tag]
  - event: [push, manual, cron]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: generate
    image: docker.io/library/golang:1.25.1
    commands:
      - go run cmd/generate.go

  - name: publish
    image: quay.io/thegeeklab/wp-git-action
    settings:
      action:
        - commit
        - push
      author_email: bot@thegeeklab.de
      author_name: thegeeklab-bot
      message: "[skip ci] automated readme update"
      netrc_password:
        from_secret: github_token
    when:
      - event: [push, manual, cron]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}

depends_on:
  - static
